Database functions
orovinskiy/UniversityTutors pull request #10
Opened 2020-04-29 22:03 UTC by dsloan92

Ready to merge. When reviewing please pull branch to ensure that the functions are working as expected. My computer, for whatever reason, is not working.

2020-04-29 23:28 UTC, kellerflint commented
- Data type required for @param in database.php (line 68,69)
- Tutor table's user_id should not AUTO_INCREMENT but it should in the User's table. The Year primary key should also AUTO_INCREMENT
- Personally I would get users/tutors by their id and not by email since a pk is more unique and it won't be hard to get because we'll have it saved to the session once they log in.

Otherwise commenting is awesome and it works on my end

2020-04-30 00:03 UTC, kellerflint requested changes
- Data type required for @param in database.php (line 68,69)
- Tutor table's user_id should not AUTO_INCREMENT but it should in the User's table. The Year primary key should also AUTO_INCREMENT
- Personally I would get users/tutors by their id and not by email since a pk is more unique and it won't be hard to get because we'll have it saved to the session once they log in.

Otherwise commenting is awesome and it works on my end

2020-04-30 01:40 UTC, dsloan92 commented
Thanks for the review Keller. I made the requested changes. I agree about using the userID instead of email, that has been changed.

2020-04-30 01:49 UTC, kellerflint requested changes

2020-04-30 01:49 UTC, kellerflint commented on model/database.php
> +                    where User.user_email = ?
where User.user_id =?

2020-04-30 02:08 UTC, merged